### ISSUE TITLE
Personal Node Connection Status doesn't Update when Changing Privacy Mode

### ISSUE THREAD

**Issue by PeteClubSeven** [Foundation-Devices/envoy#1157]
### What mobile OS are you using?

Android

### Please provide details on the device you experienced the bug on

Android:
- Device: Google Pixel 8
- Version: 14

### Description

Current Behaviour:
If you change the "Privacy mode" option from "Better Performance" to "Improve Privacy" and you set a personal node, if that personal node is unable to connect you'll see an error message stating "Couldn't reach node." If you then switch back to "Better Performance" the message doesn't change. You have to modify the personal node address to get the app to retry the connection and report success

Expected Behaviour:
When changing "Privacy Mode" the app should retry the connection to your currently selected node and update any connection/error strings

### Please provide the steps that you've used to reproduce the issue

1. Install the app
2. Finish the onboarding flow
3. Tap the "Privacy" tab
4. Set "Privacy mode" to "Better Performance"
5. Change the "Node" setting to "Improved Privacy"
6. Enter the address of an electrum node on clearnet
7. Wait until you get a failure message stating "Couldn't reach node"
8. Tap "Better Performance"
9. Notice how the error message is still visible and nothing changes
10. Modify the node field to an incorrect value and then a correct value
11. Notice how the error message disappears and is replaced by a successful connection message

### Anything else?

I just wanted to log this in case you thought it was a UX issue you wanted to know about and fix.

### Impact of the issue

{"label"=>"Low: Minor issue with minimal impact on usability."}

### If you found any similar or related issues, provide links to them here.

N/A

**Comment by BitcoinQnA** [comment]
This was fixed in v1.7. Thank you for the report.
