### ISSUE TITLE
Error when following instructions to build from source for iOS

### ISSUE THREAD

**Issue by satrinity402** [Foundation-Devices/envoy#42]
Dev environment:
- macOS 12.6, M1 Pro
- Android Studio w/ Flutter and Dart plugins installed

In the console window for the envoy project, I run `./build_ffi_ios.sh` and get the below error:

<img width="1352" src="https://user-images.githubusercontent.com/81394452/194210430-75993cee-1d19-4c57-8688-6ea81e8b5b01.png">

**Comment by satrinity402** [comment]
@icota I've got Homebrew installed.

- ran `brew install automake`
- ran `brew update`
-  (in the project dir) ran `./build_ffi_ios.sh

Still erroring on the same line but getting a different caused by now:
<img width="1662" src="https://user-images.githubusercontent.com/81394452/194339603-360944ed-22cc-4e3b-8ebf-b7ab9e898e82.png">

**Comment by icota** [comment]
@satrinity402 `brew install libtool`? I'll update the instructions once we crack this

**Comment by satrinity402** [comment]
That worked! Was able to run the build script successfully.

Now when I run `flutter build ipa` I get an error related to not having a Provisioning Profile with iCloud and Push Notifications feature:
<img width="1412" src="https://user-images.githubusercontent.com/81394452/194367056-f2bc42be-fd13-4061-8dce-d9c9e62ed0bb.png">

I believe "personal development teams" do not support iCloud and Push Notifications functionality. Not sure how to proceed next.

**Comment by icota** [comment]
Can you try opening `ios/Runner.xcworkspace` in XCode and select "Automatically manage signing" on the "Signing & Capabilites" tab?

Then press the play button to run on your device and let me know what happens.

**Comment by icota** [comment]
I don't think you need to pay the $99 to build Envoy. But I might be wrong... In that case we might consider having an option to disable these features

**Comment by icota** [comment]
Closing this as the instructions have been updated and "Apple Developer Program" members are able to build. 

It's on our roadmap to make it possible to configure Envoy without certain features so anyone (regardless of membership status) will be able to build. Will ping you when that happens @satrinity402
