### ISSUE TITLE
BRL fiat conversion

### ISSUE THREAD

**Issue by greenart7c3** [Foundation-Devices/envoy#425]
### **Description:**

Add BRL fiat conversion.

### **Use Case:**

Add BRL fiat conversion.

### **Implementation Ideas:**

Add BRL fiat conversion.

**Comment by icota** [comment]
We got you @greenart7c3. Support for :brazil: real coming in version 1.4

**Comment by icota** [comment]
Support added in https://github.com/Foundation-Devices/envoy/pull/467
