### ISSUE TITLE
Activity Screen

### ISSUE THREAD

**Issue by Dasails** [Foundation-Devices/envoy#693]
### **Platform:**

- [ x]  iOS
- [ ]  Android

### **App Version:**

The app version can be found under the Settings>About menu.

- Envoy Version: [1.4.0]

### **Device Details:**

**iOS:**

- Device: [iphone 15 Max Pro]
- iOS Version: [iOS 17.1.1]

### **Issue Description:**

**Current Behavior:**
[Activity screen is blank. Only shows one transaction]

**Expected Behavior:**
[see a history of all activities![image](https://github.com/Foundation-Devices/envoy/assets/117760614/0d4bc181-91ac-48f0-b78e-79d7ab83fd49)]

### **Steps to Reproduce:**

1. [First Step]
2. [Second Step]
3. [Third Step]
4. [Additional Steps, if necessary]

### **Screenshots/Screen Recordings:**

[If applicable, add screenshots or screen recordings to help explain the issue.]

### **Logs:**

[If applicable, add logs to help us diagnose the issue.]

To share your logs, head to Settings > Advanced > View Envoy Logs. From here you can save the logs as a file and add to the issue.

### **Additional Information:**

[Add any other relevant information here, such as if Tor was in use, network conditions, etc.]

### **Impact:**

- [ ]  Low: Minor issue with minimal impact on usability.
- [ ]  Medium: Moderate issue affecting usability.
- [ ]  High: Major issue severely impacting usability or app stability.

### **Related Issues:**

[If you found any similar or related issues, provide links to them here.]

**Comment by Dasails** [comment]
![image](https://github.com/Foundation-Devices/envoy/assets/117760614/ccd6a83d-4d80-4a3f-ae8f-5b6990ce1142)

**Comment by BitcoinQnA** [comment]
@Dasails feel free to send me the txt file via telegram and I can upload.

**Comment by BitcoinQnA** [comment]
[dasalis logs.txt](https://github.com/Foundation-Devices/envoy/files/13441431/dasalis.logs.txt)
