### ISSUE TITLE
Security Tab Issues

### ISSUE THREAD

**Issue by Dasails** [Foundation-Devices/envoy#695]
[logs 2.txt](https://github.com/Foundation-Devices/envoy/files/13443982/logs.2.txt)
### **Platform:**

- [X]  iOS

### **App Version:**

The app version can be found under the Settings>About menu.

- Envoy Version: [e.g., 1.4.0]

### **Device Details:**

**iOS:**

- Device: [iPhone 15 Pro Max]
- iOS Version: [e.g., iOS 17.1.1]

### **Issue Description:**

**Current Behavior:**
Screen turns grey and becomes inoperable when switching from personal node to Foundation node.(security tab)

**Expected Behavior:**
 Should be able to navigate options without having to restart app 

### **Screenshots/Screen Recordings:**

[If applicable, add screenshots or screen recordings to help explain the issue.]

### **Logs:**

[[](ssl://)

- [ ]  Low: Minor issue with minimal impact on usability.
- [ ]  Medium: Moderate issue affecting usability.
- [ ]  High: Major issue severely impacting usability or app stability.

### **Related Issues:**

[If you found any similar or related issues, provide links to them here.]https://github.com/Foundation-Devices/envoy/assets/117760614/54cf3fda-468f-4c96-8ac8-154a9fa92d6d

**Comment by icota** [comment]
Fixed in https://github.com/Foundation-Devices/envoy/pull/711
