### ISSUE TITLE
Swipe not intuitive

### ISSUE THREAD

**Issue by expatri0tic** [Foundation-Devices/envoy#715]
### **Platform:**
iOS

### **App Version:**
Envoy Version: 1.4.0

### **Device Details:**
**iOS:**
- Device: iPhone XR
- iOS Version: iOS 17.1.1

### **Issue Description:**

**Current Behavior:**
When I'm in the ACCOUNTS menu I can swipe left and right to hide or unhide the balance. Works perfectly. But if I click into the account suddenly it's really buggy. Basically the hit box where you can swipe is only on the bottom left. It took me a while to figure this out. I thought maybe I just wasn't able to toggle the view once inside the account. But I could every now and then. Eventually I just realized that the dimensions for the area for swiping was really tiny.

**Expected Behavior:**
I expected to be able to hide and unhide the balance before or after clicking to open an account. Specifically when I open the account.

### **Steps to Reproduce:**

1. Go to accounts
2. Click on an account
3. Attempt to hide and unhide balance using top right or middle. (hint. It doesn't work)
4. Now try to hide and unhide balance from bottom left section. (hint. It works)

### **Screenshots/Screen Recordings:**

Uploading FILE 2023-11-27 20:52:24.mp4…

### **Logs:**
[logs.txt](https://github.com/Foundation-Devices/envoy/files/13474406/logs.txt)

### **Additional Information:**

Using VPN, no TOR, not connected to my own node.

### **Impact:**

Low: Minor issue with minimal impact on usability.

**Comment by expatri0tic** [comment]
## Edit
https://github.com/Foundation-Devices/envoy/assets/133897608/464e8127-8a71-4023-bba1-3bceecb4598d

_I think I posted before the video had finished uploading._

**Comment by Jacksper13** [comment]
This was addresses and should have been fixed on version 1.7.0, @expatri0tic do you think you can confirm this is no longer a problem?

**Comment by Jacksper13** [comment]
For onlookers, @expatri0tic cannot test it in his current setup, so will go ahead ans close this as it was addressed and tested on our end in Envoy 1.7.0
