### ISSUE TITLE
Duplicate rows in Activity screen when redeeming Azteco voucher

### ISSUE THREAD

**Issue by InnocuousFinch** [Foundation-Devices/envoy#743]
### **Platform:**

- [X]  iOS
- [ ]  Android

### **App Version:**

The app version can be found under the Settings>About menu.

- Envoy Version: [e.g., 1.4.0]

1.4.0 beta

**iOS:**

- Device: [iPhone 15 Pro]
- iOS Version: [iOS 17.1.2]

### **Issue Description:**

**Current Behavior:**
Duplicate entries showing up for an Azteco redemption. 

**Expected Behavior:**
Should only show the 1 row for the unconfirmed transaction after redemption. 

### **Steps to Reproduce:**

1. Redeem Azteco voucher on latest 1.4.0 beta
2. Should see it in the Activity screen (as in the screenshot provided)
### **Screenshots/Screen Recordings:**

![image](https://github.com/Foundation-Devices/envoy/assets/118941419/a15ef992-ff11-4763-9492-3c2f502c33bd)

### **Additional Information:**

Using my own node, Fulcrum v1.8.1 via Ronindojo local IP

### **Impact:**

- [X]  Low: Minor issue with minimal impact on usability.
- [ ]  Medium: Moderate issue affecting usability.
- [ ]  High: Major issue severely impacting usability or app stability.

**Comment by Jacksper13** [comment]
Fixed on https://github.com/Foundation-Devices/envoy/pull/750
