### ISSUE TITLE
Denomination error on send screen

### ISSUE THREAD

**Issue by maxtannahill** [Foundation-Devices/envoy#744]
### **Platform:**

- [x]  iOS
- [x]  Android

### **App Version:**

- Envoy Version: 1.40

### **Issue Description:**

**Current Behavior:**
Show details on send screen shows sats denomination even if amount expressed in BTC

**Expected Behavior:**
BTC ₿ to be shown when selected

### **Steps to Reproduce:**

1. Accounts, Settings, Ensure "View amount in Sats" is unselected 
2. Send transaction, select address, amount and confirm
3. Click "show details" next to amount to send
4. See that BTC amount is expressed in sats

### **Screenshots/Screen Recordings:**

https://github.com/Foundation-Devices/envoy/assets/13302849/4d443b18-6321-48d1-b534-3431b51fdaab

### **Logs:**

Not provided

### **Additional Information:**

N/A

### **Impact:**

- [ ]  Low: Minor issue with minimal impact on usability.
- [x]  Medium: Moderate issue affecting usability.
- [ ]  High: Major issue severely impacting usability or app stability.

### **Related Issues:**

None

**Comment by maxtannahill** [comment]
https://github.com/Foundation-Devices/envoy/assets/13302849/4d443b18-6321-48d1-b534-3431b51fdaab

**Comment by BitcoinQnA** [comment]
@maxtannahill in this instance, even though you had sats enabled in settings, did you enter the amount to be sent in BTC terms? If you did, the wallet will remember that setting temporarily and display the same unit back to you in the summary screen. 

Looks like this behavior has not yet been expanded to the transaction details section.

**Comment by maxtannahill** [comment]
Sats were **not** enabled in settings. Amount to be sent was set in BTC terms. Amount expressed in the details screen seems stuck in a sats denomination.

**Comment by BitcoinQnA** [comment]
Sorry, misread your initial report and am now replicating your issue. Thank you.

**Comment by icota** [comment]
Fixed in https://github.com/Foundation-Devices/envoy/pull/755
