### ISSUE TITLE
Lock image uses incorrect aspect ratio on iPhone SE 2022

### ISSUE THREAD

**Issue by PeteClubSeven** [Foundation-Devices/envoy#803]
### **Platform:**

- [x]  iOS
- [ ] Android

### **App Version:**

- Envoy Version: 1.4.0

### **Device Details:**

**iOS:**

- Device: iPhone SE 2022
- iOS Version: iOS 17.1.2

### **Issue Description:**

**Current Behavior:**
When "Unlock with biometrics or PIN" is enabled under "Privacy", opening the app will show a fullscreen logo with white bars on both sides when using an iPhone SE 2022 which uses a different aspect ratio than the image being displayed.

**Expected Behavior:**
The fullscreen logo should fill the screen, no white bars should be visible.

### **Steps to Reproduce:**

1. Open Envoy on an iPhone SE 2022
2. Click the "Privacy" tab at the bottom of the app
4. Enable "Unlock with biometrics or PIN"
5. Close the app
6. Open the app but don't enter the PIN or tap the fingerprint sensor
7. Notice how the fullscreen logo is displaying white bars on boths sides of the phone

### **Screenshots/Screen Recordings:**
![Screenshot 2023-12-21 at 17 16 15](https://github.com/Foundation-Devices/envoy/assets/130258664/276646cb-ac65-4f7d-9f2d-ec08abe7bc84)

### **Additional Information**
I didn't test this on Android.

### **Impact:**

- [x]  Low: Minor issue with minimal impact on usability.
- [ ]  Medium: Moderate issue affecting usability.
- [ ]  High: Major issue severely impacting usability or app stability.

**Comment by BitcoinQnA** [comment]
@PeteClubSeven  Is this still present in version 1.6.2?

**Comment by PeteClubSeven** [comment]
> @PeteClubSeven Is this still present in version 1.6.2?

Yes I just checked it and its still an issue
