### ISSUE TITLE
Can't Connect to Fulcrum Server using TLS

### ISSUE THREAD

**Issue by PeteClubSeven** [Foundation-Devices/envoy#804]
### **Platform:**

- [x]  iOS
- [ ]  Android

### **App Version:**

- Envoy Version: 1.4.0

### **Device Details:**

**iOS:**

- Device: iPhone SE 2022
- iOS Version: iOS 17.1.2

### **Issue Description:**

**Current Behavior:**
When trying to connect to a personal Fulcrum server using a LAN address it seems I'm unable to connect to my node using TLS, however plain TCP works fine. My Fulcrum server is using a self-signed certificate which could be the likely culprit

**Expected Behavior:**
Connecting to a personal Fulcrum server using TLS should work. If the server uses a self-signed certificate an option should be provided to allow it.

### **Steps to Reproduce:**

1. Host a Fulcrum server on your LAN
2. Open Envoy
3. Click "Privacy"
4. Under "Node", set the drop down to "Personal Node"
5. Enter `ssl://$YOUR_LAN_IP:50002`
6. Notice how an error is presented

### **Screenshots/Screen Recordings:**
![Screenshot 2023-12-21 at 17 10 09](https://github.com/Foundation-Devices/envoy/assets/130258664/412c0869-5157-476c-b370-56d265876386)
![Screenshot 2023-12-21 at 17 09 36](https://github.com/Foundation-Devices/envoy/assets/130258664/9829eef2-6f3b-44f1-a39b-db9a6d46437d)

### **Logs:**

The logs didn't show any errors

### **Additional Information:**

I didn't test Android. The app was set to "Better Performance". The server is confirmed working over Wi-Fi with Sparrow, Blue Wallet, Nunchuk and other wallets. Only Envoy can't connect via TLS. I did have my VPN turned on in the screenshots but I tested with it turned off and it makes no difference.

### **Impact:**

- [ ]  Low: Minor issue with minimal impact on usability.
- [x]  Medium: Moderate issue affecting usability.
- [ ]  High: Major issue severely impacting usability or app stability.

**Comment by PeteClubSeven** [comment]
It's also worth noting this prevents tor connections via TLS too, though that is less of an issue since Tor encrypts the traffic anyway.

**Comment by BitcoinQnA** [comment]
Hey, we've just had a similar report from another user who was also using a self-signed cert that is not accepted by one of the Envoy [dependencies](https://docs.rs/webpki/latest/webpki/enum.Error.html#variant.UnsupportedCertVersion). 

The other user was successful with certbot/lets encrypt.

**Comment by PeteClubSeven** [comment]
> Hey, we've just had a similar report from another user who was also using a self-signed cert that is not accepted by one of the Envoy [dependencies](https://docs.rs/webpki/latest/webpki/enum.Error.html#variant.UnsupportedCertVersion).
> 
> The other user was successful with certbot/lets encrypt.

That's probably the issue! I'll have to check later though as I'm quite busy at the moment.

**Comment by BitcoinQnA** [comment]
@PeteClubSeven  did you manage to resolve this?

**Comment by PeteClubSeven** [comment]
> @PeteClubSeven did you manage to resolve this?

No I was using a self-signed certificate so that's probably the reason it doesn't work.

**Comment by PeteClubSeven** [comment]
I'm currently syncing a node again and will check with a LetsEncrypt certificate in the next few days.

**Comment by PeteClubSeven** [comment]
Yes I can confirm that TLS works with a LetsEncrypt certificate. I do think it should be possible to use a self-signed certificate but if you are happy without that feel free to close this issue.

**Comment by BitcoinQnA** [comment]
Thanks for confirming. We'll look to add this support and surface a warning to the user if/when we detect a self-signed cert.
