### ISSUE TITLE
Issue with Privacy Settings Text Not Updating Correctly in Envoy 1.6.0 Spanish Version

### ISSUE THREAD

**Issue by witheredwave** [Foundation-Devices/envoy#959]
### What mobile OS are you using?

Android

### Please provide details on the device you experienced the bug on

Android: Device Pixel 8 (Android version: 14) Firmware: GrapheneOS

### Description

In version 1.6.0 of Envoy, I encountered an issue on the initial screen when selecting the option to configure Passport. Upon progressing to the next screen, which presents the welcome message and the choice between configuring Passport or Envoy wallet, choosing to configure Passport leads to another screen (as demonstrated in the video) where there's an option to select your privacy type (with or without Tor). When using the app in Spanish, and attempting to choose between the two privacy options, the description for the better privacy option (Tor ON) does not update correctly.

Despite selecting the better privacy option, the text remains unchanged (although the color of the word 'disabled' does change) and incorrectly suggests that "Envoy's connection will be more stable with Tor disabled, recommended for new users" for both options. This is misleading, as selecting better performance does correctly indicate Tor is disabled by default (which is correct), but selecting better privacy should update the text to reflect "activated" instead of "disabled", and the description should state that the connection will be LESS stable, in addition to indicating Tor is ACTIVATED instead of disabled.

Steps to reproduce the issue:

    1. Set your device language to Spanish.
    2. Download Envoy version 1.6.0 (or earlier).
    3. On the startup screen, select (Configure Passport).
    4. Choose privacy and observe how the text does not change when selecting better performance or better privacy.

### Please provide the steps that you've used to reproduce the issue

    1. Set your device language to Spanish.
    2. Download Envoy version 1.6.0 (or earlier).
    3. On the startup screen, select (Configure Passport).
    4. Choose privacy and observe how the text does not change when selecting better performance or better privacy.

### If applicable, add screenshots or screen recordings to help explain the issue.

https://github.com/Foundation-Devices/envoy/assets/118118253/cdcc4260-15a1-4308-aeb0-d5f61950a6f7

![photo_2024-02-24_13-18-36](https://github.com/Foundation-Devices/envoy/assets/118118253/f4b6f77a-2381-4734-b3e9-7a8301f2227e)
![photo_2024-02-24_13-18-32](https://github.com/Foundation-Devices/envoy/assets/118118253/70fd33f1-a749-4d1e-b66a-720b258505c8)

### Impact of the issue

{"label"=>"Low: Minor issue with minimal impact on usability."}

### If you found any similar or related issues, provide links to them here.

-

**Comment by BitcoinQnA** [comment]
This was fixed for 1.6 main release. @witheredwave please contact me to claim your bug bounty.
